using System.Collections;
using UnityEngine;

public class TroopManager : MonoBehaviour {

	// arena 0
	public Troop Skeleton;
	public Troop Archers;
	public Troop Knight;
	public Troop Bomber;
	public Troop SkeletonArmy;
	public Troop Musketeer;
	public Troop MiniPekka;
	public Troop BabyDragon;
	public Troop Giant;
	public Troop Prince;
	public Troop Witch;
	// arena 1
	public Troop Goblins;
	public Troop SpearGoblins;
	public Troop Valkyrie;
	// arena 2
	public Troop Minions;
	public Troop Ballon;
	public Troop GiantSkeleton;
	// arena 3
	public Troop Babarians;
	// arena 4
	public Troop HogRaider;
	public Troop InfernoDragon;
	public Troop MinionHorde;
	public Troop Pekka;
	public Troop LavaHound;
	// arena 5
	public Troop FireSpirits;
	public Troop IceWizard;
	public Troop Wizard;
	// arena 6
	public Troop SkeletonBarrel;
	public Troop Miner;
	public Troop BattleRam;
	public Troop Sparky;
	public Troop Golem;
	// arena 7
	public Troop MegaMinion;
	public Troop Guards;
	public Troop Princess;
	public Troop DarkPrince;
	public Troop ElectroWizard;
	public Troop RoyalGiant;
	public Troop EliteBarbarians;
	public Troop ThreeMusketeers;
	// arena 8
	public Troop IceSpirit;
	public Troop Bats;
	public Troop IceGolem;
	public Troop NightWitch;
	public Troop Lumberjack;
	public Troop Bowler;
	// arena 9
	public Troop GoblinGang;
	public Troop DartGoblin;
	public Troop Bandit;
	public Troop FlyingMachine;
	public Troop Hunter;
	public Troop Executioner;
	// arena 10
	public Troop RoyalGhost;
	public Troop CannonCart;
	public Troop MegaKnight;
	// arena 11
	public Troop Zappies;
	public Troop MagicalArcher;
}
